// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// wellen_wasm — WebAssembly bridge to the wellen waveform parser.
//
// Mirrors the desktop wellen_ffi crate method-for-method so that the Dart-side
// WellenWasmProvider matches the WellenProvider (FFI) semantics exactly.
//
// Input: byte buffers (Uint8Array on the JS side). No filesystem access —
// browsers cannot pass file paths, only file contents read via the File API,
// drag-and-drop, or fetch().
//
// Single-threaded: browser WASM threading (SharedArrayBuffer + COOP/COEP) is
// deliberately not used. wellen's parallel VCD parse is the desktop win;
// on the web we accept single-threaded decode in exchange for working without
// cross-origin-isolation deployment headers.
//
// Panic safety: every entry point runs inside `catch_unwind`. Panics become
// structured JsError objects so the Dart side never crashes the isolate.

#![allow(clippy::missing_safety_doc)]
#![allow(clippy::let_and_return)]

use std::collections::{HashMap, HashSet};
use std::io::Cursor;
use std::panic;

use wasm_bindgen::prelude::*;
use wellen::{
    Hierarchy, ScopeRef, ScopeType, SignalRef, TimescaleUnit, VarDirection, VarRef, VarType, simple,
};

// ── file format constants ─────────────────────────────────────────────────────

const FORMAT_UNKNOWN: i32 = 0;
const FORMAT_VCD: i32 = 1;
const FORMAT_FST: i32 = 2;
const FORMAT_GHW: i32 = 3;

// ── module init ───────────────────────────────────────────────────────────────

#[wasm_bindgen(start)]
pub fn init() {
    // Forward Rust panics to console.error with backtraces — invaluable when a
    // panic surfaces during integration testing.
    console_error_panic_hook::set_once();
}

// ── handle ─────────────────────────────────────────────────────────────────────
//
// A WellenWasm holds one open waveform. Unlike the FFI crate where the handle
// is a raw pointer, here we let JS hold a wasm-bindgen-managed reference. The
// JS side calls .free() (auto-generated by wasm-bindgen) when done.

#[wasm_bindgen]
pub struct WellenWasm {
    waveform: simple::Waveform,
    // Pre-computed name strings; indexed by Scope/Var index. Returning them
    // straight as `String` avoids re-deriving every call.
    scope_names: Vec<String>,
    var_names: Vec<String>,
    file_format: i32,
    total_transitions: u64,
    loaded_refs: HashSet<u32>,
    // Cached per-signal change counts (filled on first load).
    signal_change_counts: HashMap<u32, u64>,
}

// ── helpers ───────────────────────────────────────────────────────────────────

fn detect_format(filename: &str) -> i32 {
    match filename
        .rsplit('.')
        .next()
        .unwrap_or("")
        .to_lowercase()
        .as_str()
    {
        "vcd" => FORMAT_VCD,
        "fst" => FORMAT_FST,
        "ghw" => FORMAT_GHW,
        _ => FORMAT_UNKNOWN,
    }
}

fn detect_format_from_bytes(bytes: &[u8]) -> i32 {
    // Magic-byte detection for the binary formats; VCD is ASCII text, so the
    // fallback handles it.
    if bytes.len() >= 8 && &bytes[0..1] == b"\xf2" {
        // FST starts with 0xf2 0xff 0xee... (block-type byte 0xf2).
        return FORMAT_FST;
    }
    if bytes.len() >= 4 && &bytes[0..4] == b"GHDL" {
        // GHW header begins with "GHDL".
        return FORMAT_GHW;
    }
    // VCD starts with text — usually $date or $timescale or $version.
    if bytes.len() >= 8 && (bytes.starts_with(b"$") || bytes.starts_with(b"\n$")) {
        return FORMAT_VCD;
    }
    FORMAT_UNKNOWN
}

fn scope_type_to_int(st: ScopeType) -> i32 {
    match st {
        ScopeType::Module => 0,
        ScopeType::Task => 1,
        ScopeType::Function => 2,
        ScopeType::Begin => 3,
        ScopeType::Fork => 4,
        ScopeType::Generate => 5,
        ScopeType::Struct => 6,
        ScopeType::Union => 7,
        ScopeType::Class => 8,
        ScopeType::Interface => 9,
        ScopeType::Package => 10,
        ScopeType::Program => 11,
        ScopeType::VhdlArchitecture => 20,
        ScopeType::VhdlProcedure => 21,
        ScopeType::VhdlFunction => 22,
        ScopeType::VhdlRecord => 23,
        ScopeType::VhdlProcess => 24,
        ScopeType::VhdlBlock => 25,
        ScopeType::VhdlForGenerate => 26,
        ScopeType::VhdlIfGenerate => 27,
        ScopeType::VhdlGenerate => 28,
        ScopeType::VhdlPackage => 29,
        ScopeType::GhwGeneric => 30,
        ScopeType::VhdlArray => 31,
        _ => 0,
    }
}

fn var_type_to_int(vt: VarType) -> i32 {
    match vt {
        VarType::Event => 0,
        VarType::Integer => 1,
        VarType::Parameter => 2,
        VarType::Real => 3,
        VarType::Reg => 4,
        VarType::Supply0 => 5,
        VarType::Supply1 => 6,
        VarType::Time => 7,
        VarType::Tri => 8,
        VarType::TriAnd => 9,
        VarType::TriOr => 10,
        VarType::TriReg => 11,
        VarType::Tri0 => 12,
        VarType::Tri1 => 13,
        VarType::WAnd => 14,
        VarType::Wire => 15,
        VarType::WOr => 16,
        VarType::String => 17,
        VarType::Port => 18,
        VarType::SparseArray => 19,
        VarType::RealTime => 20,
        VarType::Bit => 30,
        VarType::Logic => 31,
        VarType::Int => 32,
        VarType::ShortInt => 33,
        VarType::LongInt => 34,
        VarType::Byte => 35,
        VarType::Enum => 36,
        VarType::ShortReal => 37,
        VarType::Boolean => 40,
        VarType::BitVector => 41,
        VarType::StdLogic => 42,
        VarType::StdLogicVector => 43,
        VarType::StdULogic => 44,
        VarType::StdULogicVector => 45,
        VarType::RealParameter => 46,
        // wellen 0.24 added EventParameter (a parameter of `event` type). Same code as
        // the desktop FFI crate so web and desktop continue to parse identically.
        VarType::EventParameter => 47,
    }
}

fn var_dir_to_int(d: VarDirection) -> i32 {
    match d {
        VarDirection::Unknown => 0,
        VarDirection::Implicit => 1,
        VarDirection::Input => 2,
        VarDirection::Output => 3,
        VarDirection::InOut => 4,
        VarDirection::Buffer => 5,
        VarDirection::Linkage => 6,
    }
}

fn timescale_unit_exp(u: TimescaleUnit) -> i32 {
    match u {
        TimescaleUnit::FemtoSeconds => -15,
        TimescaleUnit::PicoSeconds => -12,
        TimescaleUnit::NanoSeconds => -9,
        TimescaleUnit::MicroSeconds => -6,
        TimescaleUnit::MilliSeconds => -3,
        TimescaleUnit::Seconds => 0,
        TimescaleUnit::AttoSeconds => -18,
        TimescaleUnit::ZeptoSeconds => -21,
        TimescaleUnit::Unknown => i32::MIN,
    }
}

fn hier(handle: &WellenWasm) -> &Hierarchy {
    handle.waveform.hierarchy()
}

fn into_js_err(e: impl std::fmt::Display) -> JsValue {
    JsError::new(&format!("{e}")).into()
}

fn run_guarded<F, R>(f: F) -> Result<R, JsValue>
where
    F: FnOnce() -> Result<R, JsValue> + std::panic::UnwindSafe,
{
    match panic::catch_unwind(f) {
        Ok(r) => r,
        Err(_) => Err(JsError::new("wellen_wasm: internal panic").into()),
    }
}

// ── lifecycle ─────────────────────────────────────────────────────────────────

#[wasm_bindgen]
impl WellenWasm {
    /// Open a waveform from a byte buffer.
    ///
    /// `filename` is the user-visible filename (used for extension-based
    /// format detection); the file contents come from `bytes`. Returns a
    /// `WellenWasm` handle that must be `.free()`d by the JS caller.
    #[wasm_bindgen(constructor)]
    pub fn new(filename: &str, bytes: &[u8]) -> Result<WellenWasm, JsValue> {
        let filename_owned = filename.to_string();
        let bytes_owned = bytes.to_vec();
        run_guarded(move || {
            let format_by_ext = detect_format(&filename_owned);
            let format_by_magic = detect_format_from_bytes(&bytes_owned);
            let file_format = if format_by_ext != FORMAT_UNKNOWN {
                format_by_ext
            } else {
                format_by_magic
            };

            // wellen's read_from_reader needs BufRead + Seek + Send + Sync + 'static.
            // Cursor<Vec<u8>> satisfies all of these.
            let cursor = Cursor::new(bytes_owned);
            let waveform = simple::read_from_reader(cursor).map_err(into_js_err)?;

            let h = waveform.hierarchy();
            // Indexed by `ScopeRef::index()` / `VarRef::index()`, which is what
            // the JS side hands back. Placed by index rather than collected in
            // iteration order: since wellen 0.25 `all_scopes()` / `all_vars()`
            // walk the tree recursively, so their order is no longer the
            // storage order the refs count in.
            let mut scope_names: Vec<String> = Vec::new();
            for s in h.all_scopes() {
                let i = s.index();
                if scope_names.len() <= i {
                    scope_names.resize_with(i + 1, String::new);
                }
                scope_names[i] = h[s].name(h).to_string();
            }
            let mut var_names: Vec<String> = Vec::new();
            for v in h.all_vars() {
                let i = v.index();
                if var_names.len() <= i {
                    var_names.resize_with(i + 1, String::new);
                }
                var_names[i] = h[v].name(h).to_string();
            }

            Ok(WellenWasm {
                waveform,
                scope_names,
                var_names,
                file_format,
                total_transitions: 0,
                loaded_refs: HashSet::new(),
                signal_change_counts: HashMap::new(),
            })
        })
    }

    // ── metadata ───────────────────────────────────────────────────────────────

    /// Return file format identifier (1 = VCD, 2 = FST, 3 = GHW, 0 = unknown).
    #[wasm_bindgen(js_name = fileFormat)]
    pub fn file_format(&self) -> i32 {
        self.file_format
    }

    /// Return the last time in the time table (simulation end time in ticks).
    ///
    /// Returned as `f64` rather than `u64` so the JS-side caller gets a plain
    /// Number — simulation times fit in 53 bits comfortably and avoiding the
    /// BigInt round-trip simplifies the Dart-side js_interop bindings.
    #[wasm_bindgen(js_name = timeEnd)]
    pub fn time_end(&self) -> f64 {
        self.waveform.time_table().last().copied().unwrap_or(0) as f64
    }

    /// Return the simulation date string (from the file header), or empty if
    /// absent.
    #[wasm_bindgen(js_name = date)]
    pub fn date(&self) -> String {
        hier(self).date().to_string()
    }

    /// Return the simulator version string, or empty if absent.
    #[wasm_bindgen(js_name = version)]
    pub fn version(&self) -> String {
        hier(self).version().to_string()
    }

    /// Return the timescale factor (1 if no timescale), and the unit exponent
    /// as a power of 10 (e.g. -9 for nanoseconds). The factor is encoded in
    /// the high 32 bits of the returned u64; the unit-exponent (i32 cast to
    /// u32) is encoded in the low 32 bits. Returns `0` (factor=0,
    /// unitExp=i32::MIN treated as "no timescale") when the file declared
    /// none.
    #[wasm_bindgen(js_name = timescale)]
    pub fn timescale(&self) -> JsValue {
        match hier(self).timescale() {
            Some(ts) => {
                let obj = js_sys::Object::new();
                let _ = js_sys::Reflect::set(
                    &obj,
                    &JsValue::from_str("factor"),
                    &JsValue::from_f64(ts.factor as f64),
                );
                let _ = js_sys::Reflect::set(
                    &obj,
                    &JsValue::from_str("unitExp"),
                    &JsValue::from_f64(timescale_unit_exp(ts.unit) as f64),
                );
                obj.into()
            }
            None => JsValue::NULL,
        }
    }

    // ── hierarchy counts ───────────────────────────────────────────────────────

    /// Total number of scopes in the hierarchy.
    #[wasm_bindgen(js_name = numScopes)]
    pub fn num_scopes(&self) -> u32 {
        self.scope_names.len() as u32
    }

    /// Total number of variables in the hierarchy.
    #[wasm_bindgen(js_name = numVars)]
    pub fn num_vars(&self) -> u32 {
        self.var_names.len() as u32
    }

    // ── root-level items ───────────────────────────────────────────────────────

    /// Return indices of all top-level scopes as a Uint32Array (packed via
    /// transmute to u32 — scope indices in wellen always fit).
    #[wasm_bindgen(js_name = rootScopes)]
    pub fn root_scopes(&self) -> Vec<u32> {
        hier(self).scopes().map(|s| s.index() as u32).collect()
    }

    /// Return indices of all top-level variables.
    #[wasm_bindgen(js_name = rootVars)]
    pub fn root_vars(&self) -> Vec<u32> {
        hier(self).vars().map(|v| v.index() as u32).collect()
    }

    // ── scope properties ───────────────────────────────────────────────────────

    /// Return the name of the scope at `scope_idx`, or empty if out of range.
    #[wasm_bindgen(js_name = scopeName)]
    pub fn scope_name(&self, scope_idx: u32) -> String {
        self.scope_names
            .get(scope_idx as usize)
            .cloned()
            .unwrap_or_default()
    }

    /// Return the scope type identifier (see `scope_type_to_int` for mapping).
    /// Returns -1 if scope_idx is out of range.
    #[wasm_bindgen(js_name = scopeType)]
    pub fn scope_type(&self, scope_idx: u32) -> i32 {
        match ScopeRef::from_index(scope_idx as usize) {
            Some(sr) => scope_type_to_int(hier(self)[sr].scope_type()),
            None => -1,
        }
    }

    /// Return the child scope indices of `scope_idx`.
    #[wasm_bindgen(js_name = scopeChildScopes)]
    pub fn scope_child_scopes(&self, scope_idx: u32) -> Vec<u32> {
        match ScopeRef::from_index(scope_idx as usize) {
            Some(sr) => hier(self)[sr]
                .scopes(hier(self))
                .map(|s| s.index() as u32)
                .collect(),
            None => Vec::new(),
        }
    }

    /// Return the child variable indices of `scope_idx`.
    #[wasm_bindgen(js_name = scopeChildVars)]
    pub fn scope_child_vars(&self, scope_idx: u32) -> Vec<u32> {
        match ScopeRef::from_index(scope_idx as usize) {
            Some(sr) => hier(self)[sr]
                .vars(hier(self))
                .map(|v| v.index() as u32)
                .collect(),
            None => Vec::new(),
        }
    }

    // ── variable properties ────────────────────────────────────────────────────

    /// Return the variable name at `var_idx`, or empty if out of range.
    #[wasm_bindgen(js_name = varName)]
    pub fn var_name(&self, var_idx: u32) -> String {
        self.var_names
            .get(var_idx as usize)
            .cloned()
            .unwrap_or_default()
    }

    /// Return the variable type identifier. Returns -1 on error.
    #[wasm_bindgen(js_name = varType)]
    pub fn var_type(&self, var_idx: u32) -> i32 {
        match VarRef::from_index(var_idx as usize) {
            Some(vr) => var_type_to_int(hier(self)[vr].var_type()),
            None => -1,
        }
    }

    /// Return the variable direction identifier. Returns -1 on error.
    #[wasm_bindgen(js_name = varDirection)]
    pub fn var_direction(&self, var_idx: u32) -> i32 {
        match VarRef::from_index(var_idx as usize) {
            Some(vr) => var_dir_to_int(hier(self)[vr].direction()),
            None => -1,
        }
    }

    /// Return the bit-width of the variable (0 if unavailable / not a bit vec).
    #[wasm_bindgen(js_name = varLength)]
    pub fn var_length(&self, var_idx: u32) -> u32 {
        match VarRef::from_index(var_idx as usize) {
            Some(vr) => hier(self)[vr].length(hier(self)).unwrap_or(0),
            None => 0,
        }
    }

    /// Return the signal-ref (opaque u32) used for load_signal and value queries.
    /// Returns u32::MAX on error.
    #[wasm_bindgen(js_name = varSignalRef)]
    pub fn var_signal_ref(&self, var_idx: u32) -> u32 {
        match VarRef::from_index(var_idx as usize) {
            Some(vr) => hier(self)[vr].signal_ref().index() as u32,
            None => u32::MAX,
        }
    }

    // ── signal loading ─────────────────────────────────────────────────────────

    /// Load signal data for `signal_ref`. Returns the change count (also
    /// cached internally). Returns 0 on error. Return value is `f64` because
    /// JS Numbers fit ~53 bits of integer precision — more than enough for any
    /// transition count we ship.
    #[wasm_bindgen(js_name = loadSignal)]
    pub fn load_signal(&mut self, signal_ref: u32) -> f64 {
        let sr = match SignalRef::from_index(signal_ref as usize) {
            Some(s) => s,
            None => return 0.0,
        };
        self.waveform.load_signals(&[sr]);
        // Cache change count.
        let count = self
            .waveform
            .get_signal(sr)
            .map(|s| s.iter_changes().count() as u64)
            .unwrap_or(0);
        if self.loaded_refs.insert(signal_ref) {
            self.total_transitions += count;
        }
        self.signal_change_counts.insert(signal_ref, count);
        count as f64
    }

    /// Unload a previously loaded signal.
    #[wasm_bindgen(js_name = unloadSignal)]
    pub fn unload_signal(&mut self, signal_ref: u32) {
        let sr = match SignalRef::from_index(signal_ref as usize) {
            Some(s) => s,
            None => return,
        };
        self.waveform.unload_signals(&[sr]);
        self.loaded_refs.remove(&signal_ref);
        self.signal_change_counts.remove(&signal_ref);
    }

    // ── value queries ──────────────────────────────────────────────────────────

    /// Return the signal value at the given simulation tick, as a string.
    /// Returns empty string if the signal is not loaded or has no value at/before `time`.
    /// `time` is `f64` (JS Number) — simulation times fit in 53 bits.
    #[wasm_bindgen(js_name = valueAt)]
    pub fn value_at(&self, signal_ref: u32, time: f64) -> String {
        let time_u64 = time as u64;
        let sr = match SignalRef::from_index(signal_ref as usize) {
            Some(s) => s,
            None => return String::new(),
        };
        let signal = match self.waveform.get_signal(sr) {
            Some(s) => s,
            None => return String::new(),
        };
        let time_table = self.waveform.time_table();
        let tbl_idx = match time_table.partition_point(|&t| t <= time_u64) {
            0 => return String::new(),
            pos => (pos - 1) as u32,
        };
        let offset = match signal.get_offset(tbl_idx) {
            Some(o) => o,
            None => return String::new(),
        };
        let val = signal.get_value_at(&offset, 0);
        val.to_string()
    }

    /// Return all value changes for `signal_ref` in `[start_time, end_time)`
    /// as a JS object: `{ times: Float64Array, values: string[] }`. The two
    /// arrays are the same length; index i in `times` corresponds to the same
    /// transition as index i in `values`. Times are encoded as `f64` (JS
    /// Number) — simulation times fit in 53 bits.
    #[wasm_bindgen(js_name = signalChanges)]
    pub fn signal_changes(&self, signal_ref: u32, start_time: f64, end_time: f64) -> JsValue {
        let start_u64 = start_time as u64;
        let end_u64 = end_time as u64;
        let sr = match SignalRef::from_index(signal_ref as usize) {
            Some(s) => s,
            None => return js_sys::Object::new().into(),
        };
        let signal = match self.waveform.get_signal(sr) {
            Some(s) => s,
            None => return js_sys::Object::new().into(),
        };
        let time_table = self.waveform.time_table();

        let mut times = Vec::<f64>::new();
        let mut values = Vec::<String>::new();
        for (tbl_idx, val) in signal.iter_changes() {
            let t = time_table[tbl_idx as usize];
            if t >= end_u64 {
                break;
            }
            if t >= start_u64 {
                times.push(t as f64);
                values.push(val.to_string());
            }
        }

        let obj = js_sys::Object::new();
        let times_arr = js_sys::Float64Array::from(times.as_slice());
        let values_arr = js_sys::Array::new_with_length(values.len() as u32);
        for (i, v) in values.iter().enumerate() {
            values_arr.set(i as u32, JsValue::from_str(v));
        }
        let _ = js_sys::Reflect::set(&obj, &JsValue::from_str("times"), &times_arr);
        let _ = js_sys::Reflect::set(&obj, &JsValue::from_str("values"), &values_arr);
        obj.into()
    }

    /// Find the next value change strictly after `after_time`.
    /// Returns `{ time, value }` (time as JS Number) or `null` if none.
    #[wasm_bindgen(js_name = nextTransition)]
    pub fn next_transition(&self, signal_ref: u32, after_time: f64) -> JsValue {
        let after_u64 = after_time as u64;
        let sr = match SignalRef::from_index(signal_ref as usize) {
            Some(s) => s,
            None => return JsValue::NULL,
        };
        let signal = match self.waveform.get_signal(sr) {
            Some(s) => s,
            None => return JsValue::NULL,
        };
        let time_table = self.waveform.time_table();
        for (tbl_idx, val) in signal.iter_changes() {
            let t = time_table[tbl_idx as usize];
            if t > after_u64 {
                let obj = js_sys::Object::new();
                let _ = js_sys::Reflect::set(
                    &obj,
                    &JsValue::from_str("time"),
                    &JsValue::from_f64(t as f64),
                );
                let _ = js_sys::Reflect::set(
                    &obj,
                    &JsValue::from_str("value"),
                    &JsValue::from_str(&val.to_string()),
                );
                return obj.into();
            }
        }
        JsValue::NULL
    }

    /// Find the last value change strictly before `before_time`.
    /// Returns `{ time, value }` (time as JS Number) or `null` if none.
    #[wasm_bindgen(js_name = prevTransition)]
    pub fn prev_transition(&self, signal_ref: u32, before_time: f64) -> JsValue {
        let before_u64 = before_time as u64;
        let sr = match SignalRef::from_index(signal_ref as usize) {
            Some(s) => s,
            None => return JsValue::NULL,
        };
        let signal = match self.waveform.get_signal(sr) {
            Some(s) => s,
            None => return JsValue::NULL,
        };
        let time_table = self.waveform.time_table();
        let mut found: Option<(u64, String)> = None;
        for (tbl_idx, val) in signal.iter_changes() {
            let t = time_table[tbl_idx as usize];
            if t >= before_u64 {
                break;
            }
            found = Some((t, val.to_string()));
        }
        match found {
            Some((t, v)) => {
                let obj = js_sys::Object::new();
                let _ = js_sys::Reflect::set(
                    &obj,
                    &JsValue::from_str("time"),
                    &JsValue::from_f64(t as f64),
                );
                let _ =
                    js_sys::Reflect::set(&obj, &JsValue::from_str("value"), &JsValue::from_str(&v));
                obj.into()
            }
            None => JsValue::NULL,
        }
    }

    // ── diagnostics ─────────────────────────────────────────────────────────────

    /// Total transitions across all loaded signals. Returned as `f64` so the
    /// JS-side caller gets a plain Number — counts fit in 53 bits even for
    /// very large captures.
    #[wasm_bindgen(js_name = totalTransitionCount)]
    pub fn total_transition_count(&self) -> f64 {
        self.total_transitions as f64
    }

    /// Transition count for a single signal. Returns 0 if not loaded.
    #[wasm_bindgen(js_name = signalTransitionCount)]
    pub fn signal_transition_count(&self, signal_ref: u32) -> f64 {
        self.signal_change_counts
            .get(&signal_ref)
            .copied()
            .unwrap_or(0) as f64
    }

    /// Approximate memory usage in bytes — same formula as the FFI crate.
    #[wasm_bindgen(js_name = memoryUsageBytes)]
    pub fn memory_usage_bytes(&self) -> f64 {
        let time_bytes = self.waveform.time_table().len() as u64 * 8;
        let hier_bytes = self.scope_names.len() as u64 * 200 + self.var_names.len() as u64 * 100;
        let signal_bytes = self.total_transitions * 16;
        (time_bytes + hier_bytes + signal_bytes) as f64
    }
}

// ── ABI version ────────────────────────────────────────────────────────────────
//
// JS callers check this before they instantiate; bumping the constant signals a
// breaking change in the JS shape.

/// The wellen_wasm ABI version. JS callers should reject mismatches.
#[wasm_bindgen(js_name = abiVersion)]
pub fn abi_version() -> u32 {
    1
}

// ── tests ─────────────────────────────────────────────────────────────────────
//
// These exercise the crate's pure logic (format detection, helpers). They run
// as native Rust tests via `cargo test` — they do not require a browser. The
// full WellenWasm/JS integration is covered by Dart-side Chrome-headless
// integration tests in `test/services/waveform/wellen_wasm_provider_test.dart`.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_format_by_extension() {
        assert_eq!(detect_format("dump.vcd"), FORMAT_VCD);
        assert_eq!(detect_format("dump.VCD"), FORMAT_VCD);
        assert_eq!(detect_format("/path/to/dump.fst"), FORMAT_FST);
        assert_eq!(detect_format("dump.ghw"), FORMAT_GHW);
        assert_eq!(detect_format("noext"), FORMAT_UNKNOWN);
        assert_eq!(detect_format("dump.fsdb"), FORMAT_UNKNOWN);
    }

    #[test]
    fn detect_format_by_magic_bytes() {
        // VCD begins with `$date` / `$timescale` / `$comment` etc.
        let vcd = b"$date Today $end\n$timescale 1ns $end\n";
        assert_eq!(detect_format_from_bytes(vcd), FORMAT_VCD);

        // FST first byte 0xf2 marks the block-type header.
        let fst = [0xf2u8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00];
        assert_eq!(detect_format_from_bytes(&fst), FORMAT_FST);

        // GHW header begins with "GHDL".
        let ghw = b"GHDLWAVE_HEADER";
        assert_eq!(detect_format_from_bytes(ghw), FORMAT_GHW);

        // Random bytes — unknown.
        let garbage = b"\xab\xcd\xef\x12\x34\x56\x78\x9a";
        assert_eq!(detect_format_from_bytes(garbage), FORMAT_UNKNOWN);
    }

    #[test]
    fn timescale_unit_exp_mapping() {
        assert_eq!(timescale_unit_exp(TimescaleUnit::FemtoSeconds), -15);
        assert_eq!(timescale_unit_exp(TimescaleUnit::PicoSeconds), -12);
        assert_eq!(timescale_unit_exp(TimescaleUnit::NanoSeconds), -9);
        assert_eq!(timescale_unit_exp(TimescaleUnit::MicroSeconds), -6);
        assert_eq!(timescale_unit_exp(TimescaleUnit::MilliSeconds), -3);
        assert_eq!(timescale_unit_exp(TimescaleUnit::Seconds), 0);
        assert_eq!(timescale_unit_exp(TimescaleUnit::Unknown), i32::MIN);
    }

    #[test]
    fn abi_version_constant() {
        // The Dart-side expectedAbiVersion must match this — bumping one
        // without bumping the other is a code-review-blocking error.
        assert_eq!(abi_version(), 1);
    }
}
