// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Static guard for the iOS launch screen.
///
/// Flutter's template ships a 1×1 transparent PNG as the launch image, centred
/// on a hardcoded white storyboard background. That produced a
/// full-brightness white flash on every cold start — worst on a dark-mode OLED
/// phone — and made `flutter build ipa` warn "Launch image is set to the
/// default placeholder icon". It is also the kind of unfinished-looking detail
/// that fed the App Store Guideline 2.2 rejection of 0.1.0 (2).
///
/// The real assets are generated by `tool/generate_ios_launch_images.swift`
/// from the master app icon. This test fails if they are ever reverted to the
/// placeholder — most plausibly by regenerating the iOS runner from the
/// Flutter template, which is exactly the kind of change whose side effects
/// nobody re-checks by hand.
void main() {
  const imagesetDir = 'ios/Runner/Assets.xcassets/LaunchImage.imageset';

  group('iOS launch image is not the Flutter placeholder', () {
    // The stock placeholder is a 1×1 PNG of 68 bytes. Any real mark is orders
    // of magnitude larger, so a generous floor catches the placeholder without
    // pinning us to a particular icon's byte count.
    const minimumPlausibleBytes = 1024;

    for (final name in const [
      'LaunchImage.png',
      'LaunchImage@2x.png',
      'LaunchImage@3x.png',
    ]) {
      test('$name is a real image', () {
        final file = File('$imagesetDir/$name');
        expect(
          file.existsSync(),
          isTrue,
          reason:
              '$name is missing — regenerate with '
              '`swift tool/generate_ios_launch_images.swift`',
        );
        expect(
          file.lengthSync(),
          greaterThan(minimumPlausibleBytes),
          reason:
              "$name looks like Flutter's 1x1 placeholder (68 bytes). "
              'Regenerate with `swift tool/generate_ios_launch_images.swift`.',
        );
      });
    }

    test('the scales are distinct renders, not one image copied thrice', () {
      // A copy-paste "fix" that puts the same file at all three scales renders
      // blurry on @2x/@3x. Sizes must strictly increase.
      final sizes = [
        File('$imagesetDir/LaunchImage.png').lengthSync(),
        File('$imagesetDir/LaunchImage@2x.png').lengthSync(),
        File('$imagesetDir/LaunchImage@3x.png').lengthSync(),
      ];
      expect(sizes[1], greaterThan(sizes[0]));
      expect(sizes[2], greaterThan(sizes[1]));
    });
  });

  test('launch storyboard does not flash white', () {
    // `red="1" green="1" blue="1"` is the template's hardcoded white. The
    // background must be the icon's dark navy instead — see
    // tool/generate_ios_launch_images.swift for why it is fixed across
    // appearances rather than light/dark-aware.
    final storyboard = File('ios/Runner/Base.lproj/LaunchScreen.storyboard');
    expect(storyboard.existsSync(), isTrue);

    final xml = storyboard.readAsStringSync();
    final backgroundColor = RegExp(
      '<color key="backgroundColor"[^>]*>',
    ).firstMatch(xml)?.group(0);
    expect(
      backgroundColor,
      isNotNull,
      reason: 'launch storyboard has no backgroundColor',
    );
    expect(
      backgroundColor,
      isNot(contains('red="1" green="1" blue="1"')),
      reason:
          'launch background is back to the template white, which flashes at '
          'full brightness on every cold start',
    );
  });

  test('the launch-image generator is committed alongside its output', () {
    // The imageset README points at this script; a missing generator turns the
    // PNGs into unreproducible hand-made artifacts that will drift from the
    // app icon.
    expect(File('tool/generate_ios_launch_images.swift').existsSync(), isTrue);
    expect(File('$imagesetDir/README.md').existsSync(), isTrue);
  });
}
