// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// Bundle-size regression gate for the lxt2fst WebAssembly artifact.
//
// The gzipped wasm is capped at 400 KiB so
// the Flutter Web build stays lean — a regression here means a
// dependency or build flag has bloated the wasm artifact and we should
// investigate before merging.
//
// The committed artefact lives at `web/wasm/lxt2fst_bg.wasm` and is
// regenerated by `dart run tool/build_lxt2fst_wasm.dart`. CI also runs
// that script + this gate against a fresh build, so this test catches
// regressions equally on developer machines and in CI.
//
// Mirrors `wellen_wasm_bundle_size_test.dart`.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

const _wasmPath = 'web/wasm/lxt2fst_bg.wasm';
const _maxGzippedBytes = 409600; // 400 KiB — fetched on the first LXT/LXT2 open

void main() {
  group('lxt2fst bundle size', () {
    test('wasm artefact is committed under web/wasm/', () {
      final file = File(_wasmPath);
      expect(
        file.existsSync(),
        isTrue,
        reason:
            'Expected $_wasmPath to exist. Run '
            '`dart run tool/build_lxt2fst_wasm.dart` to regenerate.',
      );
    });

    test('gzipped wasm stays within the 400 KiB budget', () {
      final file = File(_wasmPath);
      if (!file.existsSync()) {
        // The artefact-existence test above will already fail; skip
        // here to keep the failure message focused.
        return;
      }
      final raw = file.readAsBytesSync();
      final gz = gzip.encode(raw);
      expect(
        gz.length,
        lessThanOrEqualTo(_maxGzippedBytes),
        reason:
            'Gzipped wasm grew to ${gz.length} bytes '
            '(${(gz.length / 1024).toStringAsFixed(1)} KiB); budget is '
            '$_maxGzippedBytes bytes '
            '(${(_maxGzippedBytes / 1024).toStringAsFixed(1)} KiB). '
            'Investigate which crate feature/flag bloated the bundle — '
            'the module is fetched on the first LXT/LXT2 open, so its size is '
            'that latency.',
      );
    });

    test('loader JS is present alongside the wasm artefact', () {
      final js = File('web/wasm/lxt2fst.js');
      expect(
        js.existsSync(),
        isTrue,
        reason:
            'The wasm-bindgen JS glue must be committed alongside the '
            'wasm binary; rerun `dart run tool/build_lxt2fst_wasm.dart`.',
      );
    });
  });
}
