// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// Bundle-size regression gate for the wellen_wasm WebAssembly artifact.
//
// The gzipped wasm is capped at 1.5 MB so the
// Flutter Web build stays lean — a regression here means a dependency or
// build flag has bloated the wasm artifact and we should investigate before
// merging.
//
// The committed artefact lives at `web/wasm/wellen_wasm_bg.wasm` and is
// regenerated by `dart run tool/build_web_wasm.dart`. CI also runs that
// script + this gate against a fresh build, so this test catches regressions
// equally on developer machines and in CI.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

const _wasmPath = 'web/wasm/wellen_wasm_bg.wasm';
const _maxGzippedBytes =
    1572864; // 1.5 MiB — every web user downloads it before the first open

void main() {
  group('wellen_wasm bundle size', () {
    test('wasm artefact is committed under web/wasm/', () {
      final file = File(_wasmPath);
      expect(
        file.existsSync(),
        isTrue,
        reason:
            'Expected $_wasmPath to exist. Run '
            '`dart run tool/build_web_wasm.dart` to regenerate.',
      );
    });

    test('gzipped wasm stays within the 1.5 MB budget', () {
      final file = File(_wasmPath);
      if (!file.existsSync()) {
        // The artefact-existence test above will already fail; skip here to
        // keep the failure message focused.
        return;
      }
      final raw = file.readAsBytesSync();
      final gz = gzip.encode(raw);
      expect(
        gz.length,
        lessThanOrEqualTo(_maxGzippedBytes),
        reason:
            'Gzipped wasm grew to ${gz.length} bytes '
            '(${(gz.length / 1024).toStringAsFixed(1)} KiB); budget is '
            '$_maxGzippedBytes bytes '
            '(${(_maxGzippedBytes / 1024).toStringAsFixed(1)} KiB). '
            'Investigate which crate feature/flag bloated the bundle — '
            'every web user downloads the module before the first open.',
      );
    });

    test('loader JS is present alongside the wasm artefact', () {
      final js = File('web/wasm/wellen_wasm.js');
      expect(
        js.existsSync(),
        isTrue,
        reason:
            'The wasm-bindgen JS glue must be committed alongside the '
            'wasm binary; rerun `dart run tool/build_web_wasm.dart`.',
      );

      final loader = File('web/wasm/wellen_wasm_loader.js');
      expect(
        loader.existsSync(),
        isTrue,
        reason: 'The Dart-facing loader shim wellen_wasm_loader.js is missing.',
      );
    });
  });
}
