// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// Generates wide-signal-count VCD fixtures for performance / scroll-jank
// verification of the viewport-gated waveform loading path.
//
// These fixtures are deliberately LARGE (a 2000-signal file is tens of MB) and
// are therefore NOT committed — they exceed the per-fixture corpus cap. Run
// this tool to (re)produce them locally when you want to exercise scale:
//
//   dart run tool/generate_scale_fixtures.dart
//       → writes the default scale set to build/scale_fixtures/
//
//   dart run tool/generate_scale_fixtures.dart --out /tmp/wc --signals 2000
//       → a single 2000-signal file at a custom location
//
// Flags:
//   --out <dir>                  output directory (default build/scale_fixtures)
//   --signals <n>                generate a single file with n signals
//   --transitions-per-signal <t> avg transitions per signal (default 3500,
//                                matching forencich_axi_register density)
//   --duration <ticks>           total time span (default 1000000)
//   --seed <n>                   PRNG seed for deterministic output (default 42)
//
// With no --signals flag the default set {300, 1000, 2000, 5000} is produced.
// Output is deterministic for a given seed so re-runs are byte-identical.

import 'dart:io';
import 'dart:math';

const _defaultScales = <int>[300, 1000, 2000, 5000];

Future<void> main(List<String> args) async {
  final opts = _parse(args);
  final outDir = Directory(opts.out)..createSync(recursive: true);

  final scales = opts.signals != null ? <int>[opts.signals!] : _defaultScales;
  for (final n in scales) {
    final file = File('${outDir.path}/scale_${n}sig.vcd');
    final transitions = await _writeVcd(
      file,
      signalCount: n,
      transitionsPerSignal: opts.transitionsPerSignal,
      duration: opts.duration,
      seed: opts.seed,
    );
    final mb = (file.lengthSync() / (1024 * 1024)).toStringAsFixed(1);
    stdout.writeln(
      'wrote ${file.path}  '
      '($n signals, ~$transitions transitions, $mb MB)',
    );
  }
  stdout.writeln(
    '\nLoad one in WaveCrux, right-click the `top` scope → '
    '"Add All in Scope", and watch the status-bar progress indicator + '
    'incremental fill, then scroll to confirm no jank.',
  );
}

/// Writes a VCD with [signalCount] signals under a single `top` scope and
/// returns the total transition count emitted.
///
/// Roughly a third of the signals are multi-bit buses (8/16/32-bit) and the
/// rest are scalars, mirroring a real RTL dump. Each signal toggles at
/// deterministic pseudo-random times so the aggregate transition count lands
/// near `signalCount * transitionsPerSignal`.
Future<int> _writeVcd(
  File file, {
  required int signalCount,
  required int transitionsPerSignal,
  required int duration,
  required int seed,
}) async {
  final rng = Random(seed);
  final sink = file.openWrite();

  // Identifier codes: VCD allows printable ASCII 33..126. Use a base-94
  // encoding so thousands of signals each get a unique short code.
  String idCode(int i) {
    final buf = StringBuffer();
    var v = i;
    do {
      buf.writeCharCode(33 + (v % 94));
      v ~/= 94;
    } while (v > 0);
    return buf.toString();
  }

  final widths = <int>[];
  for (var i = 0; i < signalCount; i++) {
    // ~1 in 3 signals is a bus; rotate the bus width across 8/16/32.
    widths.add(i % 3 == 0 ? const [8, 16, 32][(i ~/ 3) % 3] : 1);
  }

  // ── Header ────────────────────────────────────────────────────────────────
  sink
    ..writeln(r'$date generated by generate_scale_fixtures.dart $end')
    ..writeln(r'$version WaveCrux scale fixture $end')
    ..writeln(r'$timescale 1ns $end')
    ..writeln(r'$scope module top $end');
  for (var i = 0; i < signalCount; i++) {
    final w = widths[i];
    sink.writeln(
      '\$var wire $w ${idCode(i)} sig$i${w > 1 ? ' [${w - 1}:0]' : ''} \$end',
    );
  }
  // ── Initial values at t=0 ─────────────────────────────────────────────────
  sink
    ..writeln(r'$upscope $end')
    ..writeln(r'$enddefinitions $end')
    ..writeln(r'$dumpvars');
  for (var i = 0; i < signalCount; i++) {
    if (widths[i] == 1) {
      sink.writeln('0${idCode(i)}');
    } else {
      sink.writeln('b${'0' * widths[i]} ${idCode(i)}');
    }
  }
  sink.writeln(r'$end');

  // ── Value changes ─────────────────────────────────────────────────────────
  //
  // Build a time-ordered stream: for each signal, schedule ~transitionsPerSignal
  // changes at random times, then emit grouped by timestamp. To avoid holding
  // millions of events in memory we walk time in fixed steps and, at each step,
  // toggle a deterministic subset of signals sized to hit the target density.
  var total = 0;
  final steps = transitionsPerSignal;
  final dt = (duration / steps).floor().clamp(1, duration);
  // Per step, how many signals change (so signals*steps changes overall).
  for (var s = 1; s <= steps; s++) {
    final t = s * dt;
    sink.writeln('#$t');
    for (var i = 0; i < signalCount; i++) {
      // Each signal changes every step (dense) — that yields
      // signalCount * steps transitions. Stagger phase so they don't all align.
      final w = widths[i];
      if (w == 1) {
        sink.writeln('${(s + i) & 1}${idCode(i)}');
      } else {
        final value = rng.nextInt(1 << (w >= 31 ? 31 : w));
        sink.writeln('b${value.toRadixString(2)} ${idCode(i)}');
      }
      total++;
    }
  }

  await sink.flush();
  await sink.close();
  return total;
}

class _Opts {
  _Opts({
    required this.out,
    required this.signals,
    required this.transitionsPerSignal,
    required this.duration,
    required this.seed,
  });
  final String out;
  final int? signals;
  final int transitionsPerSignal;
  final int duration;
  final int seed;
}

_Opts _parse(List<String> args) {
  var out = 'build/scale_fixtures';
  int? signals;
  var tps = 3500;
  var duration = 1000000;
  var seed = 42;
  for (var i = 0; i < args.length - 1; i++) {
    switch (args[i]) {
      case '--out':
        out = args[++i];
      case '--signals':
        signals = int.parse(args[++i]);
      case '--transitions-per-signal':
        tps = int.parse(args[++i]);
      case '--duration':
        duration = int.parse(args[++i]);
      case '--seed':
        seed = int.parse(args[++i]);
    }
  }
  return _Opts(
    out: out,
    signals: signals,
    transitionsPerSignal: tps,
    duration: duration,
    seed: seed,
  );
}
