// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Auto-generated Dart FFI bindings for the user-contributed decoder plugin C ABI declared in `include/wavecrux_decoder.h`. Re-generate with: dart run ffigen --config ffigen_decoder.yaml
///
class WavecruxDecoderAbi {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WavecruxDecoderAbi(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WavecruxDecoderAbi.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int wavecrux_decoder_abi_version() {
    return _wavecrux_decoder_abi_version();
  }

  late final _wavecrux_decoder_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'wavecrux_decoder_abi_version',
      );
  late final _wavecrux_decoder_abi_version = _wavecrux_decoder_abi_versionPtr
      .asFunction<int Function()>();

  int wavecrux_decoder_register(
    ffi.Pointer<WcDecoderDef> out_defs,
    ffi.Pointer<ffi.Size> inout_count,
  ) {
    return _wavecrux_decoder_register(
      out_defs,
      inout_count,
    );
  }

  late final _wavecrux_decoder_registerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<WcDecoderDef>, ffi.Pointer<ffi.Size>)
        >
      >('wavecrux_decoder_register');
  late final _wavecrux_decoder_register = _wavecrux_decoder_registerPtr
      .asFunction<
        int Function(ffi.Pointer<WcDecoderDef>, ffi.Pointer<ffi.Size>)
      >();

  ffi.Pointer<ffi.Char> wavecrux_decoder_plugin_name() {
    return _wavecrux_decoder_plugin_name();
  }

  late final _wavecrux_decoder_plugin_namePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'wavecrux_decoder_plugin_name',
      );
  late final _wavecrux_decoder_plugin_name = _wavecrux_decoder_plugin_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> wavecrux_decoder_plugin_description() {
    return _wavecrux_decoder_plugin_description();
  }

  late final _wavecrux_decoder_plugin_descriptionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'wavecrux_decoder_plugin_description',
      );
  late final _wavecrux_decoder_plugin_description =
      _wavecrux_decoder_plugin_descriptionPtr
          .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

typedef WcDecoderHandle = ffi.Pointer<ffi.Void>;

final class WcSample extends ffi.Struct {
  @ffi.Uint64()
  external int timestamp_fs;

  external ffi.Pointer<ffi.Uint8> bits_ptr;

  @ffi.Uint32()
  external int bit_width;

  @ffi.Uint32()
  external int _reserved0;
}

final class WcTransaction extends ffi.Struct {
  @ffi.Uint64()
  external int start_fs;

  @ffi.Uint64()
  external int end_fs;

  external ffi.Pointer<ffi.Char> label;

  external ffi.Pointer<ffi.Char> fields_json;

  @ffi.Uint32()
  external int is_error;

  @ffi.Uint32()
  external int _reserved0;
}

typedef WcDecoderCreateFn =
    ffi.Pointer<
      ffi.NativeFunction<
        WcDecoderHandle Function(ffi.Pointer<ffi.Char> config_json)
      >
    >;
typedef WcDecoderFeedFn =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          WcDecoderHandle handle,
          ffi.Pointer<WcSample> sample,
          ffi.Pointer<WcTransaction> out_transactions,
          ffi.Pointer<ffi.Size> inout_count,
        )
      >
    >;
typedef WcDecoderFlushFn =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          WcDecoderHandle handle,
          ffi.Pointer<WcTransaction> out_transactions,
          ffi.Pointer<ffi.Size> inout_count,
        )
      >
    >;
typedef WcDecoderDestroyFn =
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(WcDecoderHandle handle)>>;

final class WcDecoderDef extends ffi.Struct {
  external ffi.Pointer<ffi.Char> id;

  external ffi.Pointer<ffi.Char> display_name;

  external ffi.Pointer<ffi.Char> manifest_json;

  external WcDecoderCreateFn create;

  external WcDecoderFeedFn feed;

  external WcDecoderFlushFn flush;

  external WcDecoderDestroyFn destroy;

  external ffi.Pointer<ffi.Void> _reserved0;

  @ffi.Uint64()
  external int _reserved1;
}

const int WAVECRUX_DECODER_ABI_MAJOR = 1;

const int WAVECRUX_DECODER_ABI_MINOR = 2;

const int WAVECRUX_DECODER_ABI_VERSION = 65538;

const int WC_DECODER_OK = 0;

const int WC_DECODER_ERR = 1;

const int WC_DECODER_NEED_MORE_SLOTS = 2;
