// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// integration_test/coexistence/decoder_xtrace_coexistence_test.dart
//
// Decoder + X-Trace coexistence.
//
// Loads a fixture that carries both an SPI bus and an X-able `data_out` wire,
// activates the SPI decoder, then runs an X-origin trace on `data_out` at the
// time it goes `x`. Asserts the two features coexist:
//
//   * X-Trace activates and produces at least one causal-chain entry (the
//     traced signal is the root) — the X-Trace panel has content to show.
//   * The SPI decoder's transactions are unchanged by the trace (the decode
//     overlay remains intact and is not corrupted).
//   * The X-Trace panel renders in the bottom dock (it out-prioritises the
//     transaction table) without an unhandled exception.
//
// Fixture: `protocol/multi/spi_xtrace.vcd`, generated by
// `tool/generate_spi_xtrace_fixture.dart`. See
// `verification/VERIFICATION_GUIDE.md` §22.9 "Decoder + X-Trace coexistence".

import 'dart:async';

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:wavecrux/domain/models/signal_filter.dart';
import 'package:wavecrux/features/cursors/providers/cursor_providers.dart';
import 'package:wavecrux/features/decoders/providers/active_decoders_provider.dart';
import 'package:wavecrux/features/tabs/providers/tab_providers.dart';
import 'package:wavecrux/features/viewer/providers/panel_layout_provider.dart';
import 'package:wavecrux/features/viewer/providers/signal_group_providers.dart';
import 'package:wavecrux/features/viewer/providers/waveform_source_provider.dart';
import 'package:wavecrux/features/viewer/providers/x_trace_provider.dart';
import 'package:wavecrux/features/viewer/widgets/x_trace_panel.dart';
import 'package:wavecrux/services/tabs/tab_container_manager.dart';

import '../helpers/app_driver.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  suppressPlatformSemanticsLeak();

  testWidgets(
    'X-Trace runs alongside an active SPI decoder without corrupting it',
    (tester) async {
      await tester.binding.setSurfaceSize(const Size(1600, 1000));
      addTearDown(() => tester.binding.setSurfaceSize(null));

      await loadFixtureVcd(tester, 'protocol/multi/spi_xtrace.vcd');
      await activateDecoder(tester, 'SPI');

      final root = rootContainer(tester);
      final tab = root.read(tabListProvider).first;
      final container = root
          .read(tabContainerManagerProvider)
          .containerFor(tab.id);

      // SPI decode is in place before the trace.
      final spiBefore = container
          .read(activeDecodersProvider)
          .firstWhere((d) => d.decoderId == 'spi');
      final spiTxnCountBefore = spiBefore.transactions.length;
      expect(spiTxnCountBefore, greaterThan(0));

      // Add data_out to the viewer and preload it so the X marker has a lane
      // and the trace can read its value synchronously.
      final source = container.read(waveformSourceProvider).value!;
      final dataOut = source
          .findVariables(const SignalFilter())
          .firstWhere((v) => v.name == 'data_out');
      await source.loadSignal(dataOut.signalRef);
      container.read(signalGroupsProvider.notifier).addSignal(dataOut);
      await tester.pump();

      // Cursor at T=620 ns, where data_out is fully x.
      container.read(cursorStateProvider.notifier).placePrimary(620);
      await tester.pump();

      // Run the X-origin trace. traceX loads signals via the FFI isolate to
      // walk the causal chain; pump frames in a bounded poll so it completes
      // (a direct `await` here does not pump and can stall the FFI handshake).
      unawaited(
        container.read(xTraceProvider.notifier).traceX(dataOut.signalRef, 620),
      );
      for (var i = 0; i < 100; i++) {
        await tester.pump(const Duration(milliseconds: 100));
        final s = container.read(xTraceProvider);
        if (s.isActive || s.error != null) break;
      }

      final xTrace = container.read(xTraceProvider);
      expect(xTrace.error, isNull, reason: 'trace must not error at an x time');
      expect(
        xTrace.isActive,
        isTrue,
        reason: 'X-Trace must be active after tracing an x signal',
      );
      expect(
        xTrace.involvedSignalPaths,
        isNotEmpty,
        reason: 'the causal chain must contain at least the traced signal',
      );

      // The SPI overlay survives the trace untouched.
      final spiAfter = container
          .read(activeDecodersProvider)
          .firstWhere((d) => d.decoderId == 'spi');
      expect(
        spiAfter.transactions.length,
        spiTxnCountBefore,
        reason: 'running X-Trace must not drop the SPI decode overlay',
      );

      // Show the bottom dock — X-Trace out-prioritises the transaction table,
      // so the X-Trace panel renders. Panel visibility is per-tab; set it on
      // this tab's own container.
      container
          .read(panelLayoutProvider.notifier)
          .setTransactionViewVisible(visible: true);
      for (var i = 0; i < 20; i++) {
        await tester.pump(const Duration(milliseconds: 50));
        if (find.byType(XTracePanel).evaluate().isNotEmpty) break;
      }
      expect(find.byType(XTracePanel), findsOneWidget);

      expect(tester.takeException(), isNull);
    },
  );
}
