// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// integration_test/coexistence/multi_decoder_coexistence_test.dart
//
// Multi-decoder simultaneous correctness.
//
// Loads a combined VCD that carries BOTH an SPI bus (scope `spi_tb`) and an
// I²C bus (scope `i2c_tb`), activates the SPI decoder and the I²C decoder on
// their respective signal bindings, and asserts that the two decoders coexist
// without interfering:
//
//   * Each decoder produces exactly the transaction count in its own
//     `.expected_transactions.json` companion (SPI on `spi_tb`, I²C on
//     `i2c_tb`) — neither bus's decode is corrupted by the other's presence.
//   * Panning the viewport does not drop or duplicate either decoder's
//     transactions (decode state is computed once and is viewport-independent).
//   * No unhandled exception is thrown.
//
// The two decoders are added directly through `activeDecodersProvider` with
// explicit signal bindings (rather than driving the picker UI twice) so the
// scenario is deterministic; the single-decoder picker UI flow is already
// covered by `integration_test/decoders/{spi,i2c}_integration_test.dart`.
//
// Fixture: `protocol/multi/spi_i2c_basic.vcd` (+ its two expected companions),
// generated by `tool/generate_multi_coexistence_fixture.dart`. See
// `verification/VERIFICATION_GUIDE.md` §15.7 "Multi-decoder simultaneous
// correctness".
//
// A second scenario below generalizes this to all 5 open-core decoders
// (SPI, I²C, UART, AXI4-Lite, APB) simultaneously, against
// `protocol/multi/all5_basic.vcd` (+ its five expected companions),
// generated by the same tool's `_generateAllFiveFixture`.

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:wavecrux/domain/models/decoder_config.dart';
import 'package:wavecrux/domain/models/signal_filter.dart';
import 'package:wavecrux/features/decoders/providers/active_decoders_provider.dart';
import 'package:wavecrux/features/tabs/providers/tab_providers.dart';
import 'package:wavecrux/features/viewer/providers/navigation_provider.dart';
import 'package:wavecrux/features/viewer/providers/waveform_source_provider.dart';
import 'package:wavecrux/services/tabs/tab_container_manager.dart';

import '../helpers/app_driver.dart';

int _expectedTransactionCount(String relativePath) {
  final file = File(
    [
      Directory.current.path,
      'verification',
      'fixtures',
      relativePath,
    ].join(Platform.pathSeparator),
  );
  final decoded = jsonDecode(file.readAsStringSync()) as List<dynamic>;
  return decoded.length;
}

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  suppressPlatformSemanticsLeak();

  testWidgets(
    'SPI and I²C decoders coexist on a combined bus with correct counts',
    (tester) async {
      final spiExpected = _expectedTransactionCount(
        'protocol/multi/spi_i2c_basic.spi.expected_transactions.json',
      );
      final i2cExpected = _expectedTransactionCount(
        'protocol/multi/spi_i2c_basic.i2c.expected_transactions.json',
      );

      await loadFixtureVcd(tester, 'protocol/multi/spi_i2c_basic.vcd');

      final root = rootContainer(tester);
      final tab = root.read(tabListProvider).first;
      final container = root
          .read(tabContainerManagerProvider)
          .containerFor(tab.id);

      final source = container.read(waveformSourceProvider).value!;
      final vars = source.findVariables(const SignalFilter());
      String refFor(String name) =>
          vars.firstWhere((v) => v.name == name).signalRef;

      // Bind each decoder to its own bus's signals (disjoint).
      final decoders = container.read(activeDecodersProvider.notifier)
        ..addDecoder(
          'spi',
          DecoderConfig(
            signalBindings: {
              'sclk': refFor('sclk'),
              'mosi': refFor('mosi'),
              'miso': refFor('miso'),
              'cs': refFor('cs'),
            },
          ),
        )
        ..addDecoder(
          'i2c',
          DecoderConfig(
            signalBindings: {
              'scl': refFor('scl'),
              'sda': refFor('sda'),
            },
          ),
        );

      // Run both decoders. decodeAll loads the bound signals via the FFI
      // isolate; pump frames in a bounded poll so the load + decode complete.
      unawaited(decoders.decodeAll());
      for (var i = 0; i < 100; i++) {
        await tester.pump(const Duration(milliseconds: 100));
        final ds = container.read(activeDecodersProvider);
        if (ds.length == 2 && ds.every((d) => d.transactions.isNotEmpty)) break;
      }

      List<int> decoderCounts() {
        final ds = container.read(activeDecodersProvider);
        final spi = ds.firstWhere((d) => d.decoderId == 'spi');
        final i2c = ds.firstWhere((d) => d.decoderId == 'i2c');
        return [spi.transactions.length, i2c.transactions.length];
      }

      final before = decoderCounts();
      expect(
        before[0],
        spiExpected,
        reason: 'SPI transaction count must match the spi expected companion',
      );
      expect(
        before[1],
        i2cExpected,
        reason: 'I²C transaction count must match the i2c expected companion',
      );

      // Pan the viewport — scrolling must not re-decode in a way that drops
      // or duplicates either decoder's transactions.
      final nav = container.read(navigationProvider.notifier);
      for (var i = 0; i < 3; i++) {
        nav.panRight();
        await tester.pump(const Duration(milliseconds: 16));
      }
      for (var i = 0; i < 5; i++) {
        nav.panLeft();
        await tester.pump(const Duration(milliseconds: 16));
      }

      expect(
        decoderCounts(),
        equals(before),
        reason: 'panning must not drop or duplicate either decoder',
      );

      expect(tester.takeException(), isNull);
    },
  );

  testWidgets(
    'all 5 Open Core decoders coexist on a combined bus with correct counts',
    (tester) async {
      // SPI, I²C, UART, AXI4-Lite, and APB simultaneously — the generalized
      // version of the SPI+I²C scenario above. Fixture generated by
      // `tool/generate_multi_coexistence_fixture.dart`'s
      // `_generateAllFiveFixture`, which folds all 5 open-core decoders'
      // single-bus fixtures into one VCD with 5 sibling scopes.
      const decoderIds = ['spi', 'i2c', 'uart', 'axi4_lite', 'apb'];
      final expectedCounts = {
        for (final id in decoderIds)
          id: _expectedTransactionCount(
            'protocol/multi/all5_basic.$id.expected_transactions.json',
          ),
      };

      await loadFixtureVcd(tester, 'protocol/multi/all5_basic.vcd');

      final root = rootContainer(tester);
      final tab = root.read(tabListProvider).first;
      final container = root
          .read(tabContainerManagerProvider)
          .containerFor(tab.id);

      final source = container.read(waveformSourceProvider).value!;
      final vars = source.findVariables(const SignalFilter());
      // Case-insensitive: the AXI4-Lite/APB fixtures declare upper-case
      // signal names (ACLK, PADDR, …) while their decoder bindings are
      // lower-case (aclk, paddr, …), same convention the auto-bind Tier B
      // match uses.
      String refFor(String name) => vars
          .firstWhere((v) => v.name.toLowerCase() == name.toLowerCase())
          .signalRef;

      // Bind each of the 5 decoders to its own (disjoint) bus signals.
      final decoders = container.read(activeDecodersProvider.notifier)
        ..addDecoder(
          'spi',
          DecoderConfig(
            signalBindings: {
              'sclk': refFor('sclk'),
              'mosi': refFor('mosi'),
              'miso': refFor('miso'),
              'cs': refFor('cs'),
            },
          ),
        )
        ..addDecoder(
          'i2c',
          DecoderConfig(
            signalBindings: {
              'scl': refFor('scl'),
              'sda': refFor('sda'),
            },
          ),
        )
        ..addDecoder(
          'uart',
          DecoderConfig(
            signalBindings: {
              'tx': refFor('tx'),
              'rx': refFor('rx'),
            },
            // uart_basic.vcd uses 1 Mbaud timing — see the doc comment in
            // uart_integration_test.dart for why the 9600 default can't
            // detect any frames in this fixture.
            parameters: const {'baud_rate': 1000000},
          ),
        )
        ..addDecoder(
          'axi4_lite',
          DecoderConfig(
            signalBindings: {
              'aclk': refFor('aclk'),
              'aresetn': refFor('aresetn'),
              'awaddr': refFor('awaddr'),
              'awvalid': refFor('awvalid'),
              'awready': refFor('awready'),
              'wdata': refFor('wdata'),
              'wvalid': refFor('wvalid'),
              'wready': refFor('wready'),
              'wstrb': refFor('wstrb'),
              'bresp': refFor('bresp'),
              'bvalid': refFor('bvalid'),
              'bready': refFor('bready'),
              'araddr': refFor('araddr'),
              'arvalid': refFor('arvalid'),
              'arready': refFor('arready'),
              'rdata': refFor('rdata'),
              'rresp': refFor('rresp'),
              'rvalid': refFor('rvalid'),
              'rready': refFor('rready'),
            },
          ),
        )
        ..addDecoder(
          'apb',
          DecoderConfig(
            signalBindings: {
              'pclk': refFor('pclk'),
              'presetn': refFor('presetn'),
              'psel': refFor('psel'),
              'penable': refFor('penable'),
              'pwrite': refFor('pwrite'),
              'paddr': refFor('paddr'),
              'pwdata': refFor('pwdata'),
              'prdata': refFor('prdata'),
              'pready': refFor('pready'),
              'pslverr': refFor('pslverr'),
              'pprot': refFor('pprot'),
              'pstrb': refFor('pstrb'),
            },
          ),
        );

      // Run all 5 decoders. decodeAll loads the bound signals via the FFI
      // isolate; pump frames in a bounded poll so the load + decode complete.
      unawaited(decoders.decodeAll());
      for (var i = 0; i < 150; i++) {
        await tester.pump(const Duration(milliseconds: 100));
        final ds = container.read(activeDecodersProvider);
        if (ds.length == 5 && ds.every((d) => d.transactions.isNotEmpty)) {
          break;
        }
      }

      Map<String, int> decoderCounts() {
        final ds = container.read(activeDecodersProvider);
        return {
          for (final id in decoderIds)
            id: ds.firstWhere((d) => d.decoderId == id).transactions.length,
        };
      }

      final before = decoderCounts();
      for (final id in decoderIds) {
        expect(
          before[id],
          expectedCounts[id],
          reason:
              '$id transaction count must match its expected companion — '
              'none of the other 4 buses may corrupt its decode',
        );
      }

      // Pan the viewport — scrolling must not re-decode in a way that drops
      // or duplicates any of the 5 decoders' transactions.
      final nav = container.read(navigationProvider.notifier);
      for (var i = 0; i < 3; i++) {
        nav.panRight();
        await tester.pump(const Duration(milliseconds: 16));
      }
      for (var i = 0; i < 5; i++) {
        nav.panLeft();
        await tester.pump(const Duration(milliseconds: 16));
      }

      expect(
        decoderCounts(),
        equals(before),
        reason: 'panning must not drop or duplicate any of the 5 decoders',
      );

      expect(tester.takeException(), isNull);
    },
  );
}
