// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// FST-mirror known-answer equivalence (ARCHITECTURE.md §8.9, Layer 2/3).
//
// Each hand-crafted VCD under test/fixtures/vcd/ has a committed FST mirror
// under test/fixtures/fst/ (generated by tool/generate_fst_mirrors.sh via
// GTKWave's vcd2fst). The VCD fixtures are the known-answer gold standard;
// wellen's FST front-end must read each mirror *identically* to the VCD it
// was made from. This test loads both formats through the real WellenProvider
// (FFI) and asserts they agree on the hierarchy, the time range, and every
// signal's full value-change history + sampled valueAt() — so committing the
// FST mirrors actively exercises the FST reader against ground truth instead
// of just adding inert files.
//
// Signals are matched by hierarchical path, not signalRef: the opaque ref is
// backend-specific and legitimately differs between the VCD and FST loads.
//
// Needs the wellen FFI library: skipped locally when it is not built, and a
// failure in CI, which builds it before the Dart tests.
@TestOn('vm')
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:wavecrux/domain/models/signal_filter.dart';
import 'package:wavecrux/domain/models/variable.dart';
import 'package:wavecrux/services/waveform/wellen_provider.dart';

import '../../helpers/wellen_ffi_library_gate.dart';

const _vcdDir = 'test/fixtures/vcd';
const _fstDir = 'test/fixtures/fst';

/// Fixture base names that have a committed FST mirror.
const _fixtures = <String>[
  'scalar_basics',
  'vector_formats',
  'analog_real',
  'deep_hierarchy',
  'direction_test',
];

Map<String, Variable> _byPath(WellenProvider p) => {
  for (final v in p.findVariables(const SignalFilter())) v.fullPath: v,
};

void main() {
  if (!requireWellenFfiLibrary('FST↔VCD equivalence')) return;

  for (final name in _fixtures) {
    group('FST mirror equivalence — $name', () {
      final vcdPath = '$_vcdDir/$name.vcd';
      final fstPath = '$_fstDir/$name.fst';

      late WellenProvider vcd;
      late WellenProvider fst;

      setUp(() async {
        expect(File(vcdPath).existsSync(), isTrue, reason: 'missing $vcdPath');
        expect(
          File(fstPath).existsSync(),
          isTrue,
          reason: 'missing $fstPath — run tool/generate_fst_mirrors.sh',
        );
        vcd = WellenProvider();
        fst = WellenProvider();
        await vcd.openFile(vcdPath);
        await fst.openFile(fstPath);
      });
      tearDown(() {
        vcd.close();
        fst.close();
      });

      test('time range matches', () {
        expect(fst.startTime, vcd.startTime);
        expect(fst.endTime, vcd.endTime);
      });

      test('hierarchy (paths + widths + types) matches', () {
        final vcdVars = _byPath(vcd);
        final fstVars = _byPath(fst);
        expect(
          fstVars.keys.toSet(),
          vcdVars.keys.toSet(),
          reason: 'FST and VCD must expose the same signal paths',
        );
        for (final path in vcdVars.keys) {
          expect(
            fstVars[path]!.bitWidth,
            vcdVars[path]!.bitWidth,
            reason: 'bit width mismatch for $path',
          );
          expect(
            fstVars[path]!.varType,
            vcdVars[path]!.varType,
            reason: 'var type mismatch for $path',
          );
        }
      });

      test(
        'every signal: full change history + sampled valueAt match',
        () async {
          final vcdVars = _byPath(vcd);
          final fstVars = _byPath(fst);
          final start = vcd.startTime;
          final end = vcd.endTime;

          for (final path in vcdVars.keys) {
            final vRef = vcdVars[path]!.signalRef;
            final fRef = fstVars[path]!.signalRef;
            await vcd.loadSignal(vRef);
            await fst.loadSignal(fRef);

            final vChanges = vcd.changesInRange(vRef, start, end);
            final fChanges = fst.changesInRange(fRef, start, end);
            expect(
              fChanges.map((c) => (c.time, c.value)).toList(),
              vChanges.map((c) => (c.time, c.value)).toList(),
              reason: 'change history diverges for $path',
            );

            // Sample valueAt at each transition and the midpoint after it —
            // covers wellen's repeat-value gap-fill between explicit changes.
            for (var i = 0; i < vChanges.length; i++) {
              final t = vChanges[i].time;
              expect(
                fst.valueAt(fRef, t),
                vcd.valueAt(vRef, t),
                reason: 'valueAt($path, $t) diverges',
              );
              final next = i + 1 < vChanges.length ? vChanges[i + 1].time : end;
              if (next > t + 1) {
                final mid = t + (next - t) ~/ 2;
                expect(
                  fst.valueAt(fRef, mid),
                  vcd.valueAt(vRef, mid),
                  reason: 'valueAt($path, $mid) diverges (gap-fill)',
                );
              }
            }
          }
        },
      );
    });
  }
}
