// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// GHW functional coverage — VHDL-specific type handling.
//
// WaveCrux reads GHW (GHDL's native waveform) via wellen, but had no GHW test
// at all. GHW uniquely carries VHDL richness that VCD/FST don't: the 9-value
// std_logic system, enumerations, integer/natural, arrays, and records. This
// opens the committed fixture (test/fixtures/real_world/wavecrux_vhdl_types.ghw,
// generated by tool/ghw_fixtures/regen.sh) via the real WellenProvider FFI path
// and asserts the parsed hierarchy + values, validating the GHW front-end.
//
// The corpus-wide zoo test (_real_world_zoo_test.dart) additionally smoke-tests
// that the same .ghw opens without crashing; this file pins the VHDL semantics.
@TestOn('vm')
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:wavecrux/domain/models/signal_filter.dart';
import 'package:wavecrux/services/waveform/wellen_provider_io.dart';

import '../../helpers/wellen_ffi_library_gate.dart';

const _fixture = 'test/fixtures/real_world/wavecrux_vhdl_types.ghw';
const _tb = 'wavecrux_vhdl_types_tb';

void main() {
  if (!requireWellenFfiLibrary('GHW VHDL types')) return;

  group(
    'GHW parse — VHDL-specific types',
    () {
      late WellenProvider provider;

      setUp(() async {
        provider = WellenProvider();
        await provider.openFile(_fixture);
      });
      tearDown(() {
        provider.close();
      });

      test('exposes VHDL library scopes alongside the testbench', () {
        final roots = provider.rootScopes.map((s) => s.name).toSet();
        // A GHW trait: GHDL emits the VHDL standard libraries as scopes.
        expect(
          roots,
          containsAll(<String>['std_logic_1164', 'numeric_std', _tb]),
          reason: 'GHW should surface VHDL library scopes + the testbench',
        );
      });

      test('flattens VHDL arrays + records and preserves widths', () {
        final byPath = {
          for (final v in provider.findVariables(const SignalFilter()))
            v.fullPath: v,
        };

        // std_logic_vector array `mem` → indexed members, 8-bit each.
        for (final i in [0, 1, 2, 3]) {
          final v = byPath['$_tb.mem.[$i]'];
          expect(
            v,
            isNotNull,
            reason: 'array element mem.[$i] should be present',
          );
          expect(v!.bitWidth, 8);
        }
        // record `pix` → member signals, 4-bit each.
        for (final m in ['r', 'g', 'b']) {
          final v = byPath['$_tb.pix.$m'];
          expect(
            v,
            isNotNull,
            reason: 'record member pix.$m should be present',
          );
          expect(v!.bitWidth, 4);
        }
        // scalar / vector / enum / integer widths.
        expect(byPath['$_tb.clk']!.bitWidth, 1);
        expect(byPath['$_tb.cnt']!.bitWidth, 8); // unsigned(7:0)
        expect(byPath['$_tb.num']!.bitWidth, 32); // integer
        expect(byPath['$_tb.state']!.bitWidth, 2); // enum state_t (4 values)
      });

      test('9-value std_logic: high-Z and weak drive strengths', () async {
        final byPath = {
          for (final v in provider.findVariables(const SignalFilter()))
            v.fullPath: v,
        };
        final tri = byPath['$_tb.tri']!;
        final weak = byPath['$_tb.weak']!;
        await provider.loadSignal(tri.signalRef);
        await provider.loadSignal(weak.signalRef);

        // Initial drive: high-impedance and weak-low — values VCD never carries.
        expect(provider.valueAt(tri.signalRef, provider.startTime), 'z');
        expect(provider.valueAt(weak.signalRef, provider.startTime), 'l');

        // Over the run, tri is later driven strong-'1' and weak goes weak-high.
        final triValues = provider
            .changesInRange(tri.signalRef, provider.startTime, provider.endTime)
            .map((c) => c.value)
            .toSet();
        final weakValues = provider
            .changesInRange(
              weak.signalRef,
              provider.startTime,
              provider.endTime,
            )
            .map((c) => c.value)
            .toSet();
        expect(
          triValues,
          containsAll(<String>['z', '1']),
          reason: 'tri exercises high-Z and a strong drive',
        );
        expect(
          weakValues,
          containsAll(<String>['l', 'h']),
          reason: 'weak exercises weak-low and weak-high',
        );
      });

      test('enum cycles and the counter increments', () async {
        final byPath = {
          for (final v in provider.findVariables(const SignalFilter()))
            v.fullPath: v,
        };
        final state = byPath['$_tb.state']!;
        final cnt = byPath['$_tb.cnt']!;
        await provider.loadSignal(state.signalRef);
        await provider.loadSignal(cnt.signalRef);

        expect(provider.valueAt(state.signalRef, provider.startTime), '00');

        final stateValues = provider
            .changesInRange(
              state.signalRef,
              provider.startTime,
              provider.endTime,
            )
            .map((c) => c.value)
            .toSet();
        // IDLE/LOAD/RUN/DONE → more than one distinct encoding.
        expect(
          stateValues.length,
          greaterThan(1),
          reason: 'enum state_t should cycle through multiple values',
        );

        final cntValues = provider
            .changesInRange(cnt.signalRef, provider.startTime, provider.endTime)
            .map((c) => c.value)
            .toSet();
        expect(
          cntValues.length,
          greaterThan(4),
          reason: 'cnt is a free-running counter → many distinct values',
        );
      });
    },
  );
}
