// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:wavecrux/domain/enums/timescale_unit.dart';
import 'package:wavecrux/domain/models/timescale.dart';
import 'package:wavecrux/services/export/saif_statistics.dart';

/// Emits a **backward SAIF** (Switching Activity Interchange Format) document.
///
/// SAIF is what power tools ingest: PrimePower, Joules and PowerArtist all read
/// it. Emitting one makes WaveCrux a good citizen in an existing power flow
/// rather than a competitor to it — a deliberate scope decision, which is also
/// why this file computes no watts and names nothing "power".
///
/// **What subset this is.** The document shape follows Verilator's own SAIF
/// emitter (`verilated_saif_c.cpp` in Verilator 5.x), which is the most
/// checkable reference available and produces files the mainstream tools
/// accept: `SAIFVERSION 2.0`, `DIRECTION "backward"`, a nested `INSTANCE` tree,
/// and per-bit `NET` entries carrying `T0 / T1 / TZ / TX / TB / TC`. It is not
/// the whole of IEEE 1801's SAIF — there are no `PORT` sections, no state- or
/// path-dependent `COND` groups, and no forward-direction constraint output.
///
/// **One place this beats the reference.** Verilator's writer hardcodes
/// `TZ 0 / TX 0 / TB 0` with the comment that it only has two-value logic.
/// WaveCrux reads four-state VCD/FST data, so real `x` and `z` dwell times are
/// reported. A tool that weights unknown time differently — or an engineer
/// asking why a net is unknown for 12% of the run — gets a true answer here.
class SaifWriter {
  /// Creates a writer.
  const SaifWriter();

  /// Renders the SAIF document for [signals] over a window of [duration] ticks.
  ///
  /// [timescale] supplies the `TIMESCALE` line; a null timescale falls back to
  /// `1ns`, matching how the rest of the app treats an untimed trace.
  /// [divider] is the hierarchy separator used *inside the source paths*, not
  /// the one emitted — SAIF always declares `/`.
  String render({
    required List<SaifSignalActivity> signals,
    required int duration,
    Timescale? timescale,
    String divider = '.',
    String programName = 'WaveCrux',
  }) {
    final buf = StringBuffer()
      ..writeln('// Generated by WaveCrux')
      ..writeln('(SAIFILE')
      ..writeln('(SAIFVERSION "2.0")')
      ..writeln('(DIRECTION "backward")')
      ..writeln('(PROGRAM_NAME "$programName")')
      ..writeln('(DIVIDER / )')
      ..writeln('(TIMESCALE ${_timescaleString(timescale)})')
      ..writeln('(DURATION $duration)');

    final root = _ScopeNode('');
    for (final signal in signals) {
      final parts = signal.fullPath.split(divider);
      // The leaf is the signal; everything before it is instance hierarchy.
      // A path with no divider is a signal at the root, which is legal.
      final scopes = parts.length > 1
          ? parts.sublist(0, parts.length - 1)
          : const <String>[];
      var node = root;
      for (final scope in scopes) {
        node = node.children.putIfAbsent(scope, () => _ScopeNode(scope));
      }
      node.signals.add(signal);
    }

    for (final child in root.children.values) {
      _writeScope(buf, child, 1);
    }
    // Signals directly at the root have no INSTANCE to live in. Rather than
    // invent one, emit them in a NET block at file level — a reader that
    // expects instances still parses it, and inventing a scope name would put
    // a fictional level into someone's power report.
    if (root.signals.isNotEmpty) {
      _writeNets(buf, root.signals, 1);
    }

    buf.writeln(')');
    return buf.toString();
  }

  void _writeScope(StringBuffer buf, _ScopeNode node, int depth) {
    final pad = ' ' * depth;
    buf.writeln('$pad(INSTANCE ${node.name}');
    if (node.signals.isNotEmpty) _writeNets(buf, node.signals, depth + 1);
    for (final child in node.children.values) {
      _writeScope(buf, child, depth + 1);
    }
    buf.writeln('$pad)');
  }

  void _writeNets(
    StringBuffer buf,
    List<SaifSignalActivity> signals,
    int depth,
  ) {
    final pad = ' ' * depth;
    buf.writeln('$pad(NET');
    for (final signal in signals) {
      for (var i = 0; i < signal.bits.length; i++) {
        final bit = signal.bits[i];
        // Buses are indexed per bit with escaped brackets, exactly as
        // Verilator writes them; a scalar carries no index at all.
        final label = signal.width > 1 ? '${signal.name}\\[$i\\]' : signal.name;
        buf.writeln(
          '$pad ($label (T0 ${bit.t0}) (T1 ${bit.t1}) (TZ ${bit.tz}) '
          '(TX ${bit.tx}) (TB 0) (TC ${bit.toggleCount}))',
        );
      }
    }
    buf.writeln('$pad)');
  }

  /// Formats the `TIMESCALE` value, e.g. `1ns`.
  static String _timescaleString(Timescale? timescale) {
    if (timescale == null) return '1ns';
    return '${timescale.factor}${_unitSuffix(timescale.unit)}';
  }

  static String _unitSuffix(TimescaleUnit unit) => switch (unit) {
    TimescaleUnit.seconds => 's',
    TimescaleUnit.milliSeconds => 'ms',
    TimescaleUnit.microSeconds => 'us',
    TimescaleUnit.nanoSeconds => 'ns',
    TimescaleUnit.picoSeconds => 'ps',
    TimescaleUnit.femtoSeconds => 'fs',
    TimescaleUnit.unknown => 'ns',
  };
}

class _ScopeNode {
  _ScopeNode(this.name);

  final String name;
  final Map<String, _ScopeNode> children = <String, _ScopeNode>{};
  final List<SaifSignalActivity> signals = <SaifSignalActivity>[];
}
