// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Auto-generated Dart FFI bindings for the wellen_ffi Rust crate. Re-generate with: dart run ffigen --config ffigen.yaml
///
class WellenFfi {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WellenFfi(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WellenFfi.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Open a VCD, FST, or GHW waveform file.
  /// Returns a non-null handle on success, or NULL on failure.
  /// The returned handle must be freed with wellen_close().
  ffi.Pointer<WellenHandle> wellen_open(ffi.Pointer<ffi.Char> path) {
    return _wellen_open(path);
  }

  late final _wellen_openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<WellenHandle> Function(ffi.Pointer<ffi.Char>)
        >
      >('wellen_open');
  late final _wellen_open = _wellen_openPtr
      .asFunction<ffi.Pointer<WellenHandle> Function(ffi.Pointer<ffi.Char>)>();

  /// Free a handle returned by wellen_open().
  void wellen_close(ffi.Pointer<WellenHandle> handle) {
    return _wellen_close(handle);
  }

  late final _wellen_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<WellenHandle>)>>(
        'wellen_close',
      );
  late final _wellen_close = _wellen_closePtr
      .asFunction<void Function(ffi.Pointer<WellenHandle>)>();

  /// Return the last error message (empty string if none).
  /// The returned pointer is valid until the next call on this handle.
  ffi.Pointer<ffi.Char> wellen_last_error(ffi.Pointer<WellenHandle> handle) {
    return _wellen_last_error(handle);
  }

  late final _wellen_last_errorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>)
        >
      >('wellen_last_error');
  late final _wellen_last_error = _wellen_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>)>();

  ffi.Pointer<ffi.Char> wellen_last_open_error() {
    return _wellen_last_open_error();
  }

  late final _wellen_last_open_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'wellen_last_open_error',
      );
  late final _wellen_last_open_error = _wellen_last_open_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Fill *factor_out and *unit_exp_out with the timescale.
  /// unit_exp_out is the SI exponent (e.g. -9 for nanoseconds, -12 for picoseconds).
  /// Returns 1 if a timescale is present, 0 if not.
  int wellen_get_timescale(
    ffi.Pointer<WellenHandle> handle,
    ffi.Pointer<ffi.Uint32> factor_out,
    ffi.Pointer<ffi.Int32> unit_exp_out,
  ) {
    return _wellen_get_timescale(handle, factor_out, unit_exp_out);
  }

  late final _wellen_get_timescalePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Pointer<ffi.Uint32>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('wellen_get_timescale');
  late final _wellen_get_timescale = _wellen_get_timescalePtr
      .asFunction<
        int Function(
          ffi.Pointer<WellenHandle>,
          ffi.Pointer<ffi.Uint32>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// Return the last time value in the time table (simulation end, in ticks).
  int wellen_time_end(ffi.Pointer<WellenHandle> handle) {
    return _wellen_time_end(handle);
  }

  late final _wellen_time_endPtr =
      _lookup<
        ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<WellenHandle>)>
      >('wellen_time_end');
  late final _wellen_time_end = _wellen_time_endPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>)>();

  /// Return a null-terminated string with the simulation date.
  /// Pointer is valid for the lifetime of the handle.
  ffi.Pointer<ffi.Char> wellen_date(ffi.Pointer<WellenHandle> handle) {
    return _wellen_date(handle);
  }

  late final _wellen_datePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>)
        >
      >('wellen_date');
  late final _wellen_date = _wellen_datePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>)>();

  /// Return a null-terminated string with the simulator version.
  /// Pointer is valid for the lifetime of the handle.
  ffi.Pointer<ffi.Char> wellen_version(ffi.Pointer<WellenHandle> handle) {
    return _wellen_version(handle);
  }

  late final _wellen_versionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>)
        >
      >('wellen_version');
  late final _wellen_version = _wellen_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>)>();

  /// Return the file format of the opened waveform (WELLEN_FORMAT_* constant).
  /// Returns WELLEN_FORMAT_UNKNOWN (0) if the format could not be determined
  /// from the file extension or the handle is NULL.
  int wellen_file_format(ffi.Pointer<WellenHandle> handle) {
    return _wellen_file_format(handle);
  }

  late final _wellen_file_formatPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<WellenHandle>)>
      >('wellen_file_format');
  late final _wellen_file_format = _wellen_file_formatPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>)>();

  /// Return the total number of value changes across all signals loaded so far
  /// via wellen_load_signal(). The count accumulates as more signals are loaded.
  /// Returns 0 if no signals have been loaded yet, or the handle is NULL.
  int wellen_total_transition_count(ffi.Pointer<WellenHandle> handle) {
    return _wellen_total_transition_count(handle);
  }

  late final _wellen_total_transition_countPtr =
      _lookup<
        ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<WellenHandle>)>
      >('wellen_total_transition_count');
  late final _wellen_total_transition_count = _wellen_total_transition_countPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>)>();

  /// Return the number of value changes for a specific signal_ref.
  /// The signal must first be loaded via wellen_load_signal(); returns 0 if
  /// the signal is not loaded or the handle is NULL.
  int wellen_signal_transition_count(
    ffi.Pointer<WellenHandle> handle,
    int signal_ref,
  ) {
    return _wellen_signal_transition_count(handle, signal_ref);
  }

  late final _wellen_signal_transition_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint64 Function(ffi.Pointer<WellenHandle>, ffi.Uint32)
        >
      >('wellen_signal_transition_count');
  late final _wellen_signal_transition_count =
      _wellen_signal_transition_countPtr
          .asFunction<int Function(ffi.Pointer<WellenHandle>, int)>();

  /// Return an approximate memory usage in bytes for the waveform data held by
  /// this handle. This is an estimate, not an exact allocation count:
  /// time_table entries × 8 bytes
  /// + scope metadata × 200 bytes + variable metadata × 100 bytes
  /// + loaded signal changes × 16 bytes (estimated storage per change)
  /// Returns 0 if the handle is NULL.
  int wellen_memory_usage_bytes(ffi.Pointer<WellenHandle> handle) {
    return _wellen_memory_usage_bytes(handle);
  }

  late final _wellen_memory_usage_bytesPtr =
      _lookup<
        ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<WellenHandle>)>
      >('wellen_memory_usage_bytes');
  late final _wellen_memory_usage_bytes = _wellen_memory_usage_bytesPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>)>();

  /// Total number of scopes in the hierarchy (all levels).
  int wellen_num_scopes(ffi.Pointer<WellenHandle> handle) {
    return _wellen_num_scopes(handle);
  }

  late final _wellen_num_scopesPtr =
      _lookup<
        ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<WellenHandle>)>
      >('wellen_num_scopes');
  late final _wellen_num_scopes = _wellen_num_scopesPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>)>();

  /// Total number of variables in the hierarchy (all levels).
  int wellen_num_vars(ffi.Pointer<WellenHandle> handle) {
    return _wellen_num_vars(handle);
  }

  late final _wellen_num_varsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<WellenHandle>)>
      >('wellen_num_vars');
  late final _wellen_num_vars = _wellen_num_varsPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>)>();

  /// Write up to `max` top-level scope indices into `out`.
  /// Returns the number of indices written, or -1 on error.
  int wellen_root_scopes(
    ffi.Pointer<WellenHandle> handle,
    ffi.Pointer<ffi.Uint64> out,
    int max,
  ) {
    return _wellen_root_scopes(handle, out, max);
  }

  late final _wellen_root_scopesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Pointer<ffi.Uint64>,
            ffi.Uint64,
          )
        >
      >('wellen_root_scopes');
  late final _wellen_root_scopes = _wellen_root_scopesPtr
      .asFunction<
        int Function(ffi.Pointer<WellenHandle>, ffi.Pointer<ffi.Uint64>, int)
      >();

  /// Write up to `max` top-level variable indices into `out`.
  /// Returns the number of indices written, or -1 on error.
  int wellen_root_vars(
    ffi.Pointer<WellenHandle> handle,
    ffi.Pointer<ffi.Uint64> out,
    int max,
  ) {
    return _wellen_root_vars(handle, out, max);
  }

  late final _wellen_root_varsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Pointer<ffi.Uint64>,
            ffi.Uint64,
          )
        >
      >('wellen_root_vars');
  late final _wellen_root_vars = _wellen_root_varsPtr
      .asFunction<
        int Function(ffi.Pointer<WellenHandle>, ffi.Pointer<ffi.Uint64>, int)
      >();

  /// Return the name of scope `scope_idx` as a null-terminated string.
  /// Pointer is valid for the lifetime of the handle. Returns NULL if out of range.
  ffi.Pointer<ffi.Char> wellen_scope_name(
    ffi.Pointer<WellenHandle> handle,
    int scope_idx,
  ) {
    return _wellen_scope_name(handle, scope_idx);
  }

  late final _wellen_scope_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>, ffi.Uint64)
        >
      >('wellen_scope_name');
  late final _wellen_scope_name = _wellen_scope_namePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>, int)
      >();

  /// Return the scope type (WELLEN_SCOPE_* constant), or -1 if out of range.
  int wellen_scope_type(ffi.Pointer<WellenHandle> handle, int scope_idx) {
    return _wellen_scope_type(handle, scope_idx);
  }

  late final _wellen_scope_typePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<WellenHandle>, ffi.Uint64)
        >
      >('wellen_scope_type');
  late final _wellen_scope_type = _wellen_scope_typePtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>, int)>();

  /// Write up to `max` child scope indices of `scope_idx` into `out`.
  /// Returns the count written, or -1 on error.
  int wellen_scope_child_scopes(
    ffi.Pointer<WellenHandle> handle,
    int scope_idx,
    ffi.Pointer<ffi.Uint64> out,
    int max,
  ) {
    return _wellen_scope_child_scopes(handle, scope_idx, out, max);
  }

  late final _wellen_scope_child_scopesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Uint64,
            ffi.Pointer<ffi.Uint64>,
            ffi.Uint64,
          )
        >
      >('wellen_scope_child_scopes');
  late final _wellen_scope_child_scopes = _wellen_scope_child_scopesPtr
      .asFunction<
        int Function(
          ffi.Pointer<WellenHandle>,
          int,
          ffi.Pointer<ffi.Uint64>,
          int,
        )
      >();

  /// Write up to `max` child variable indices of `scope_idx` into `out`.
  /// Returns the count written, or -1 on error.
  int wellen_scope_child_vars(
    ffi.Pointer<WellenHandle> handle,
    int scope_idx,
    ffi.Pointer<ffi.Uint64> out,
    int max,
  ) {
    return _wellen_scope_child_vars(handle, scope_idx, out, max);
  }

  late final _wellen_scope_child_varsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Uint64,
            ffi.Pointer<ffi.Uint64>,
            ffi.Uint64,
          )
        >
      >('wellen_scope_child_vars');
  late final _wellen_scope_child_vars = _wellen_scope_child_varsPtr
      .asFunction<
        int Function(
          ffi.Pointer<WellenHandle>,
          int,
          ffi.Pointer<ffi.Uint64>,
          int,
        )
      >();

  /// Return the name of variable `var_idx` as a null-terminated string.
  /// Pointer is valid for the lifetime of the handle. Returns NULL if out of range.
  ffi.Pointer<ffi.Char> wellen_var_name(
    ffi.Pointer<WellenHandle> handle,
    int var_idx,
  ) {
    return _wellen_var_name(handle, var_idx);
  }

  late final _wellen_var_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>, ffi.Uint64)
        >
      >('wellen_var_name');
  late final _wellen_var_name = _wellen_var_namePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<WellenHandle>, int)
      >();

  /// Return the variable type (WELLEN_VAR_* constant), or -1 if out of range.
  int wellen_var_type(ffi.Pointer<WellenHandle> handle, int var_idx) {
    return _wellen_var_type(handle, var_idx);
  }

  late final _wellen_var_typePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<WellenHandle>, ffi.Uint64)
        >
      >('wellen_var_type');
  late final _wellen_var_type = _wellen_var_typePtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>, int)>();

  /// Return the variable direction (WELLEN_DIR_* constant), or -1 if out of range.
  int wellen_var_direction(ffi.Pointer<WellenHandle> handle, int var_idx) {
    return _wellen_var_direction(handle, var_idx);
  }

  late final _wellen_var_directionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<WellenHandle>, ffi.Uint64)
        >
      >('wellen_var_direction');
  late final _wellen_var_direction = _wellen_var_directionPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>, int)>();

  /// Return the bit width of variable `var_idx` (0 if not a bit-vector or unavailable).
  int wellen_var_length(ffi.Pointer<WellenHandle> handle, int var_idx) {
    return _wellen_var_length(handle, var_idx);
  }

  late final _wellen_var_lengthPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<WellenHandle>, ffi.Uint64)
        >
      >('wellen_var_length');
  late final _wellen_var_length = _wellen_var_lengthPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>, int)>();

  /// Return the signal reference (opaque u32) for variable `var_idx`.
  /// Pass this value to wellen_load_signal / wellen_value_at / wellen_signal_changes.
  /// Returns UINT32_MAX on error.
  int wellen_var_signal_ref(ffi.Pointer<WellenHandle> handle, int var_idx) {
    return _wellen_var_signal_ref(handle, var_idx);
  }

  late final _wellen_var_signal_refPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<WellenHandle>, ffi.Uint64)
        >
      >('wellen_var_signal_ref');
  late final _wellen_var_signal_ref = _wellen_var_signal_refPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>, int)>();

  /// Load signal data for `signal_ref` (lazy — call before querying values).
  /// Returns 0 on success, -1 on error.
  int wellen_load_signal(ffi.Pointer<WellenHandle> handle, int signal_ref) {
    return _wellen_load_signal(handle, signal_ref);
  }

  late final _wellen_load_signalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<WellenHandle>, ffi.Uint32)
        >
      >('wellen_load_signal');
  late final _wellen_load_signal = _wellen_load_signalPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>, int)>();

  /// Unload a previously loaded signal to free memory.
  /// Returns 0 on success, -1 on error.
  int wellen_unload_signal(ffi.Pointer<WellenHandle> handle, int signal_ref) {
    return _wellen_unload_signal(handle, signal_ref);
  }

  late final _wellen_unload_signalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<WellenHandle>, ffi.Uint32)
        >
      >('wellen_unload_signal');
  late final _wellen_unload_signal = _wellen_unload_signalPtr
      .asFunction<int Function(ffi.Pointer<WellenHandle>, int)>();

  /// Write the signal value at simulation tick `time` into `value_buf` as a
  /// null-terminated bit string (e.g. "0", "1", "10x1z", "3.14").
  ///
  /// Returns bytes written (excluding null), -1 if no value available at/before
  /// `time` or signal not loaded, -2 if buffer too small.
  int wellen_value_at(
    ffi.Pointer<WellenHandle> handle,
    int signal_ref,
    int time,
    ffi.Pointer<ffi.Uint8> value_buf,
    int buf_len,
  ) {
    return _wellen_value_at(handle, signal_ref, time, value_buf, buf_len);
  }

  late final _wellen_value_atPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Uint32,
            ffi.Uint64,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
          )
        >
      >('wellen_value_at');
  late final _wellen_value_at = _wellen_value_atPtr
      .asFunction<
        int Function(
          ffi.Pointer<WellenHandle>,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// Collect all value changes in the half-open interval [start_time, end_time).
  ///
  /// out_times      — uint64 array, receives the tick of each change
  /// out_value_buf  — flat byte buffer for null-terminated value strings
  /// value_buf_len  — total capacity of out_value_buf
  /// out_offsets    — uint32 array, byte offset into out_value_buf per change
  /// max_count      — capacity of out_times and out_offsets
  ///
  /// Returns the number of changes written, -1 if signal not loaded,
  /// or -2 if any output buffer is too small.
  int wellen_signal_changes(
    ffi.Pointer<WellenHandle> handle,
    int signal_ref,
    int start_time,
    int end_time,
    ffi.Pointer<ffi.Uint64> out_times,
    ffi.Pointer<ffi.Uint8> out_value_buf,
    int value_buf_len,
    ffi.Pointer<ffi.Uint32> out_offsets,
    int max_count,
  ) {
    return _wellen_signal_changes(
      handle,
      signal_ref,
      start_time,
      end_time,
      out_times,
      out_value_buf,
      value_buf_len,
      out_offsets,
      max_count,
    );
  }

  late final _wellen_signal_changesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Uint32,
            ffi.Uint64,
            ffi.Uint64,
            ffi.Pointer<ffi.Uint64>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint32>,
            ffi.Int64,
          )
        >
      >('wellen_signal_changes');
  late final _wellen_signal_changes = _wellen_signal_changesPtr
      .asFunction<
        int Function(
          ffi.Pointer<WellenHandle>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Uint64>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint32>,
          int,
        )
      >();

  /// Find the next value change strictly after `after_time`.
  ///
  /// On success: writes change time to *out_time, value string to value_buf,
  /// and returns 1.
  /// Returns 0 if there is no next transition.
  /// Returns -1 if the signal is not loaded or an error occurred.
  /// Returns -2 if value_buf is too small.
  int wellen_next_transition(
    ffi.Pointer<WellenHandle> handle,
    int signal_ref,
    int after_time,
    ffi.Pointer<ffi.Uint64> out_time,
    ffi.Pointer<ffi.Uint8> value_buf,
    int buf_len,
  ) {
    return _wellen_next_transition(
      handle,
      signal_ref,
      after_time,
      out_time,
      value_buf,
      buf_len,
    );
  }

  late final _wellen_next_transitionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Uint32,
            ffi.Uint64,
            ffi.Pointer<ffi.Uint64>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
          )
        >
      >('wellen_next_transition');
  late final _wellen_next_transition = _wellen_next_transitionPtr
      .asFunction<
        int Function(
          ffi.Pointer<WellenHandle>,
          int,
          int,
          ffi.Pointer<ffi.Uint64>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// Find the last value change strictly before `before_time`.
  ///
  /// On success: writes change time to *out_time, value string to value_buf,
  /// and returns 1.
  /// Returns 0 if there is no previous transition.
  /// Returns -1 if the signal is not loaded or an error occurred.
  /// Returns -2 if value_buf is too small.
  int wellen_prev_transition(
    ffi.Pointer<WellenHandle> handle,
    int signal_ref,
    int before_time,
    ffi.Pointer<ffi.Uint64> out_time,
    ffi.Pointer<ffi.Uint8> value_buf,
    int buf_len,
  ) {
    return _wellen_prev_transition(
      handle,
      signal_ref,
      before_time,
      out_time,
      value_buf,
      buf_len,
    );
  }

  late final _wellen_prev_transitionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<WellenHandle>,
            ffi.Uint32,
            ffi.Uint64,
            ffi.Pointer<ffi.Uint64>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
          )
        >
      >('wellen_prev_transition');
  late final _wellen_prev_transition = _wellen_prev_transitionPtr
      .asFunction<
        int Function(
          ffi.Pointer<WellenHandle>,
          int,
          int,
          ffi.Pointer<ffi.Uint64>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();
}

final class WellenHandle extends ffi.Opaque {}

const int WELLEN_SCOPE_MODULE = 0;

const int WELLEN_SCOPE_TASK = 1;

const int WELLEN_SCOPE_FUNCTION = 2;

const int WELLEN_SCOPE_BEGIN = 3;

const int WELLEN_SCOPE_FORK = 4;

const int WELLEN_SCOPE_GENERATE = 5;

const int WELLEN_SCOPE_STRUCT = 6;

const int WELLEN_SCOPE_UNION = 7;

const int WELLEN_SCOPE_CLASS = 8;

const int WELLEN_SCOPE_INTERFACE = 9;

const int WELLEN_SCOPE_PACKAGE = 10;

const int WELLEN_SCOPE_PROGRAM = 11;

const int WELLEN_SCOPE_VHDL_ARCH = 20;

const int WELLEN_SCOPE_VHDL_PROC = 21;

const int WELLEN_SCOPE_VHDL_FUNC = 22;

const int WELLEN_SCOPE_VHDL_RECORD = 23;

const int WELLEN_SCOPE_VHDL_PROCESS = 24;

const int WELLEN_SCOPE_VHDL_BLOCK = 25;

const int WELLEN_SCOPE_VHDL_FOR_GEN = 26;

const int WELLEN_SCOPE_VHDL_IF_GEN = 27;

const int WELLEN_SCOPE_VHDL_GEN = 28;

const int WELLEN_SCOPE_VHDL_PKG = 29;

const int WELLEN_SCOPE_GHW_GENERIC = 30;

const int WELLEN_SCOPE_VHDL_ARRAY = 31;

const int WELLEN_VAR_EVENT = 0;

const int WELLEN_VAR_INTEGER = 1;

const int WELLEN_VAR_PARAMETER = 2;

const int WELLEN_VAR_REAL = 3;

const int WELLEN_VAR_REG = 4;

const int WELLEN_VAR_SUPPLY0 = 5;

const int WELLEN_VAR_SUPPLY1 = 6;

const int WELLEN_VAR_TIME = 7;

const int WELLEN_VAR_TRI = 8;

const int WELLEN_VAR_TRIAND = 9;

const int WELLEN_VAR_TRIOR = 10;

const int WELLEN_VAR_TRIREG = 11;

const int WELLEN_VAR_TRI0 = 12;

const int WELLEN_VAR_TRI1 = 13;

const int WELLEN_VAR_WAND = 14;

const int WELLEN_VAR_WIRE = 15;

const int WELLEN_VAR_WOR = 16;

const int WELLEN_VAR_STRING = 17;

const int WELLEN_VAR_PORT = 18;

const int WELLEN_VAR_SPARSE_ARRAY = 19;

const int WELLEN_VAR_REAL_TIME = 20;

const int WELLEN_VAR_BIT = 30;

const int WELLEN_VAR_LOGIC = 31;

const int WELLEN_VAR_INT = 32;

const int WELLEN_VAR_SHORT_INT = 33;

const int WELLEN_VAR_LONG_INT = 34;

const int WELLEN_VAR_BYTE = 35;

const int WELLEN_VAR_ENUM = 36;

const int WELLEN_VAR_SHORT_REAL = 37;

const int WELLEN_VAR_BOOLEAN = 40;

const int WELLEN_VAR_BIT_VECTOR = 41;

const int WELLEN_VAR_STD_LOGIC = 42;

const int WELLEN_VAR_STD_LOGIC_VEC = 43;

const int WELLEN_VAR_STD_ULOGIC = 44;

const int WELLEN_VAR_STD_ULOGIC_VEC = 45;

const int WELLEN_VAR_REAL_PARAMETER = 46;

const int WELLEN_VAR_EVENT_PARAMETER = 47;

const int WELLEN_DIR_UNKNOWN = 0;

const int WELLEN_DIR_IMPLICIT = 1;

const int WELLEN_DIR_INPUT = 2;

const int WELLEN_DIR_OUTPUT = 3;

const int WELLEN_DIR_INOUT = 4;

const int WELLEN_DIR_BUFFER = 5;

const int WELLEN_DIR_LINKAGE = 6;

const int WELLEN_FORMAT_UNKNOWN = 0;

const int WELLEN_FORMAT_VCD = 1;

const int WELLEN_FORMAT_FST = 2;

const int WELLEN_FORMAT_GHW = 3;
